# -*- coding: utf-8 -*-
"""Fine_Tuned_Phi3mini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ss_L5ahzCc7S972SZzYPU_b8zjHXdMfJ
"""

!pip install -q unsloth
!pip install -q transformers datasets accelerate peft

import json

# Load dataset
with open("50 doctor_patient_conversations.json", "r") as f:
    raw_data = json.load(f)

formatted_data = []

for conv in raw_data:
    conversation = conv.get("conversation", [])
    for i in range(len(conversation) - 1):
        first = conversation[i]
        second = conversation[i + 1]

        # Check pattern: doctor prompt followed by patient response
        if "doctor" in first and "patient" in second:
            prompt = f"Doctor: {first['doctor'].strip()}"
            response = f"Patient: {second['patient'].strip()}"
            formatted_data.append({"prompt": prompt, "response": response})

# Save cleaned dataset
output_path = "phi3_finetune_dataset_fixed.json"
with open(output_path, "w") as f:
    json.dump(formatted_data, f, indent=2)

output_path, len(formatted_data), formatted_data[0]

from datasets import load_dataset, Dataset
import json

# Load cleaned dataset
with open("/content/phi3_finetune_dataset_fixed.json", "r") as f:
    raw_data = json.load(f)

dataset = Dataset.from_list([
    {"text": f"{example['prompt']}\n{example['response']}"}
    for example in raw_data
])
print("✅ Dataset Loaded. Size:", len(dataset))
print(dataset[0])

from unsloth import FastLanguageModel
import torch

# Load model
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "microsoft/phi-3-mini-4k-instruct",
    max_seq_length = 2048,
    dtype = torch.float16,
    load_in_4bit = True,
)

# Prepare model for LoRA
model = FastLanguageModel.get_peft_model(
    model,
    r = 8,
    lora_alpha = 16,
    lora_dropout = 0.05,
    target_modules = ["self_attn.k_proj", "self_attn.v_proj'", "mlp.up_proj", "mlp.gate_proj", "mlp.down_proj"],

    bias = "none",
    use_gradient_checkpointing = True,
)

from unsloth.trainer import SFTTrainer
from transformers import TrainingArguments

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = 2048,
    dataset_num_proc = 2,
    packing = False,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 2,
        warmup_steps = 10,
        num_train_epochs = 3,
        learning_rate = 2e-4,
        fp16 = True,
        logging_steps = 10,
        output_dir = "./phi3-lora-patientbot",
        optim = "adamw_8bit",
        save_strategy = "epoch",
        report_to = "none",
    ),
)

trainer.train()

!pip install matplotlib

import matplotlib.pyplot as plt

# Extract step-wise loss values
log_history = trainer.state.log_history
steps = [entry["step"] for entry in log_history if "loss" in entry]
losses = [entry["loss"] for entry in log_history if "loss" in entry]

# Plot the loss curve
plt.figure(figsize=(8, 5))
plt.plot(steps, losses, marker='o', linestyle='-', color='blue')
plt.title("Training Loss Over Time")
plt.xlabel("Training Steps")
plt.ylabel("Loss")
plt.grid(True)
plt.tight_layout()
plt.show()

model.save_pretrained("/content/phi3-patient-chatbot-lora")
tokenizer.save_pretrained("/content/phi3-patient-chatbot-lora")

!rm -rf /content/offload

from unsloth import FastLanguageModel
from transformers import pipeline
import torch

# ✅ Load your fine-tuned LoRA model
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="/content/phi3-patient-chatbot-lora",  # update path if needed
    max_seq_length=2048,
    dtype=torch.float16,
    load_in_4bit=True,
)

# ✅ Clean any unwanted AI labels from response
def clean_response(text):
    for wrong in ["Chatmin:", "Chatbot:", "Bot:", "AI:", "Doctor:", "<|endoftext|>"]:
        text = text.replace(wrong, "")
    return text.strip()

# ✅ Generate patient-style response to doctor's question
def ask_patient(question):
    prompt = f"Doctor: {question}\nPatient:"
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    output_ids = model.generate(
        **inputs,
        max_new_tokens=100,
        temperature=0.7,
        top_p=0.9,
        do_sample=True,
        pad_token_id=tokenizer.eos_token_id,
    )

    # Decode and extract patient response
    full_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    if "Patient:" in full_text:
        response = full_text.split("Patient:")[1]
        if "Doctor:" in response:
            response = response.split("Doctor:")[0]
        return clean_response(response)
    else:
        return clean_response(full_text)

# 💬 Chat loop
print("🩺 Virtual Patient Chatbot\nType 'exit' to end.\n")

while True:
    user_input = input("Doctor: ")
    if user_input.lower() in ["exit", "quit"]:
        print("Session ended.")
        break
    patient_response = ask_patient(user_input)
    print("Patient:", patient_response)

import os

# Define save directory
save_dir = "/content/phi3-patient-chatbot-lora"
os.makedirs(save_dir, exist_ok=True)

# Save the model
model.save_pretrained(save_dir)

# Save the tokenizer
tokenizer.save_pretrained(save_dir)

print(f"Model and tokenizer saved to {save_dir}")

!zip -r phi3-patient-chatbot-lora.zip /content/phi3-patient-chatbot-lora

from google.colab import files
files.download("phi3-patient-chatbot-lora.zip")

model.save_pretrained("/content/phi3-patient-chatbot-lora")